using Solar_System;

SolarScene scene = new SolarScene();
//scene.Planets = new List<Planet>() { new Planet("earth", new Planet("sun")), new Planet("mars", new Planet("sun")) };
scene.UseMouse = true;
var sun = new Planet("sun");
Planet earth = new Planet("earth", sun);
Planet moon = new Planet("moon", earth);
Planet jupiter = new Planet("jupiter", sun);
Planet satrun = new Planet("saturn", sun);
Planet mars = new Planet("mars", sun);
Planet mercury = new Planet("mercury", sun);
Planet neptune = new Planet("neptune", sun);
Planet uranus = new Planet("uranus", sun);
//Planet venus = new Planet("venus", sun);
//Planet mooon = new Planet("mooon", venus);
scene.AddPlanet(earth);
scene.AddPlanet(sun);
scene.AddPlanet(moon);
//scene.AddPlanet(mooon);
scene.AddPlanet(jupiter);
scene.AddPlanet(satrun);
scene.AddPlanet(mars);
scene.AddPlanet(mercury);
scene.AddPlanet(neptune);
scene.planetMoon("venus", 4); 
//scene.AddPlanet(new Planet("moon", new Planet("earth")));
//scene.Planets = new List<Planet>() { new Planet("earth") };
//scene.RenderFrequency = 120;
scene.Run();