using Solar_System;

SolarScene scene = new SolarScene();
//scene.Planets = new List<Planet>() { new Planet("earth", new Planet("sun")), new Planet("mars", new Planet("sun")) };
scene.UseMouse = true;
var sun = new Planet("sun");
Planet earth = new("earth", sun);
Planet moon = new("moon", earth);
Planet jupiter = new("jupiter", sun);
Planet satrun = new("saturn", sun);
Planet mercury = new("mercury", sun);
scene.planetMoon("venus", 4);
scene.AddPlanet(earth);
scene.AddPlanet(sun);
scene.AddPlanet(moon);
scene.AddPlanet(jupiter);
scene.AddPlanet(satrun);
scene.AddPlanet(mercury);
//scene.AddPlanet(new Planet("moon", new Planet("earth")));
//scene.Planets = new List<Planet>() { new Planet("earth") };
//scene.RenderFrequency = 120;
scene.Run();